version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - /Users/B2B/Postgres/db:/var/lib/postgresql/data 
    